version: '3.8'
# docker-compose up --build

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Spring Boot Backend
  backend:
    build:
      context: ./Linux-Labyrinth
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
      - frontend
    networks:
      - app-network

  # React Frontend
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    
  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
